
class TryCatchFinallyClass {
    fun main(){

        try {

        }catch (e: Exception){
            println("Error")
        }finally {

        }
    }
}